#!/bin/sh

. /sbin/wifi detect
find_ap() {
	local config=$1
	local mode,ifname
	config_get ifname "$config" ifname
	[ -n "${ifname}" ] && {
		config_get mode "$config" mode
		[ "$mode" = "ap" ] && echo ${config}
	}
}

local section=$(config_foreach find_ap wifi-iface)
[ -n "$section" ] && {
	uci set wireless.${section}.encryption='psk'
	uci set wireless.${section}.ssid='skifta'
	uci set wireless.${section}.mode='sta'
	uci set wireless.${section}.key='12345670'
	uci set wireless.${section}.network='wan'
	uci set wireless.${section}.wps_config='push_button virtual_push_button physical_push_button display virtual_display'
	#No network.wan section in OOB configuration,so create this
	uci set network.wan='interface'
	uci set network.wan.proto='dhcp'
	uci commit
	/sbin/wifi up
}
