#!/usr/bin/lua

local sys = require "luci.sys"
local json = require "luci.json"
local io = require "io"

local has_iwinfo = pcall(require, "iwinfo")
if has_iwinfo then
    local iw = sys.wifi.getiwinfo("radio0")
    if iw then
        function scanlist(times)
            local i, k, v, m
	    local l = { }
            local s = { }
	    -- table @r: mapping ssid to the index of entry in table @l
	    local r = { }
	
	    function is_scan_entry_duplicate(a, b)
		return (a.ssid == b.ssid) and (a.mode == b.mode) and (a.encryption.wep == b.encryption.wep) and (a.encryption.wpa == b.encryption.wpa) 
	    end

	    for i = 1, times do
		for k, v in ipairs(iw.scanlist) do
			if not s[v.bssid] then
			    local duplicate = false
			    for _, m in ipairs(l) do
				if is_scan_entry_duplicate(m, v) then
				    -- found duplicate entry, do not add it
				    duplicate = true
				    break
				end
			    end
			    if not duplicate then
				l[#l + 1] = v
			    end
			end
		end
	    end
		
	    table.sort(l, function(a, b) return (tonumber(a.signal) or 999) > (tonumber(b.signal) or 999) end )

	    return l
	end
	
	local iw_scan_list = scanlist(5)
        local fout = io.open("/tmp/luci_sam_scan", "w")
        fout:write(luci.json.encode(iw_scan_list))
        fout:close()
    end
end

