#!/bin/sh

wpa_conf="/var/run/wpa_supplicant-global.conf"
wpa_ctrl="/var/run/wpa_supplicant"

ifname="tmp-ath1"

generate_wep_key() {
	local key="$1"
	local hex=1

	echo -n "$key" | grep -qE "[^a-fA-F0-9]" && hex=0
	[ "${#key}" -eq 10 -a $hex -eq 1 ] || [ "${#key}" -eq 26 -a $hex -eq 1 ] || {
		[ "${key:0:2}" = "s:" ] && key="${key#s:}"
		key="$(echo -n "$key" | hexdump -ve '1/1 "%02x"')"
	}
	echo "$key"
}

##################################
# parameters:   $1 (ssid)
#               $2 (bssid)
#               $3 (scan_freq)
#               $4 (encryption)
#               $5 (psk)
##################################
wpa_check_connection() {
	local ssid=$1
	local bssid=$2
	local scan_freq=$3
	local encrypt=$4
	local psk=$5

	local wpa_stat=
	local handshake=0
	local scanning=0
	local timeout=4
	local network=
	local status=
	network=$(wpa_cli -p${wpa_ctrl} -i${ifname} list_networks 2>/dev/null | awk -F/ '{if($1 !~ /network id/) print}' | cut -f1)
	[ -z "${network}" ] && {
		network=$(wpa_cli -p${wpa_ctrl} -i${ifname} add_network 2>/dev/null)
	}
	[ -z "${network}" ] && {
		#echo "cann't find a network to work with!!!"
		return 1
	}
	status=$(wpa_cli -p${wpa_ctrl} -i${ifname} set_network ${network} ssid \"$1\" 2>/dev/null)
	[ ${status} = "FAIL" ] && return 1
	status=$(wpa_cli -p${wpa_ctrl} -i${ifname} set_network ${network} bssid $2 2>/dev/null)
	[ ${status} = "FAIL" ] && return 1
	status=$(wpa_cli -p${wpa_ctrl} -i${ifname} set_network ${network} scan_freq $3 2>/dev/null)
	[ ${status} = "FAIL" ] && return 1
	case "${encrypt}" in
		*none*)
			status=$(wpa_cli -p${wpa_ctrl} -i${ifname} set_network ${network} key_mgmt 'NONE' 2>/dev/null)
			[ ${status} = "FAIL" ] && return 1
		;;
		*wep*)
			status=$(wpa_cli -p${wpa_ctrl} -i${ifname} set_network ${network} key_mgmt 'NONE' 2>/dev/null)
			[ ${status} = "FAIL" ] && return 1
			status=$(wpa_cli -p${wpa_ctrl} -i${ifname} set_network ${network} wep_key0 $(generate_wep_key $5) 2>/dev/null)
			[ ${status} = "FAIL" ] && return 1
			status=$(wpa_cli -p${wpa_ctrl} -i${ifname} set_network ${network} wep_tx_keyidx 0 2>/dev/null)
			[ ${status} = "FAIL" ] && return 1
		;;
		*psk*)
			status=$(wpa_cli -p${wpa_ctrl} -i${ifname} set_network ${network} key_mgmt 'WPA-PSK' 2>/dev/null)
			[ ${status} = "FAIL" ] && return 1
			status=$(wpa_cli -p${wpa_ctrl} -i${ifname} set_network ${network} psk \"$5\" 2>/dev/null)
			[ ${status} = "FAIL" ] && return 1
			case "${encrypt}" in
				*psk2*)
					status=$(wpa_cli -p${wpa_ctrl} -i${ifname} set_network ${network} proto 'RSN' 2>/dev/null)
					[ ${status} = "FAIL" ] && return 1
				;;
				*psk*)
					status=$(wpa_cli -p${wpa_ctrl} -i${ifname} set_network ${network} proto 'WPA' 2>/dev/null)
					[ ${status} = "FAIL" ] && return 1
				;;
			esac
		;;
	esac
	status=$(wpa_cli -p${wpa_ctrl} -i${ifname} enable_network ${network} 2>/dev/null)
	[ ${status} = "FAIL" ] && return 1
	wpa_cli -p${wpa_ctrl} -i${ifname} reconnect 2>/dev/null 1>&2

	while [ ${timeout} -gt 0 ]; do
		sleep 1
		wpa_stat=$(wpa_cli -p${wpa_ctrl} -i${ifname} status 2>/dev/null | grep wpa_state | cut -d= -f2)
		echo "${wpa_stat}"
		if [ ${wpa_stat} = "COMPLETED" ]; then
			break
		elif [ ${wpa_stat} = "4WAY_HANDSHAKE" ]; then
			if [ ${handshake} -eq 1 ]; then
				break
			else
				handshake=$((++handshake))
			fi
		elif [ ${wpa_stat} = "SCANNING" ]; then
			if [ ${scanning} -eq 1 ]; then
				break
			else
				scanning=$((++scanning))
			fi
		elif [ ${wpa_stat} = "DISCONNECTED" ]; then
			break
		fi
		timeout=$((--timeout))
	done

	if [ ${wpa_stat} != "COMPLETED" ]; then
		return 1
	else
		return 0
	fi
}

channel_to_freq() {
	if [ $1 -ge 1 -a $1 -le 11 ]; then
		echo $(( ($1-1)*5+2412 ))
	elif [ $1 -ge 36 -a $1 -le 64 ]; then
		echo $(( ($1-36)*5+5180 ))
	elif [ $1 -ge 100 -a $1 -le 150 ]; then
		echo $(( ($1-100)*5+5500 ))
	else
		return 1
	fi

	return 0
}

. /lib/functions.sh

[ $# -ne 5  ] && return 2

channel_to_freq $3 || return 2

apvap=$(iwconfig 2>/dev/null | awk -F' ' '/ESSID/ {print $1}')
config_load wireless
config_get apchannel wifi0 channel

[ -d /sys/class/net/${ifname} ] || wlanconfig ${ifname} create wlandev wifi0 wlanmode sta 2>/dev/null 1>&2
[ -f /var/run/wpa_supplicant.pid ] || wpa_supplicant -B -g${wpa_conf} -P/var/run/wpa_supplicant.pid 2>/dev/null 1>&2

wpa_cli -g${wpa_conf} interface_add ${ifname} "" athr /var/run/wpa_supplicant 2>/dev/null 1>&2

wpa_check_connection $1 $2 $(channel_to_freq $3) $4 $5 && {
	wpa_cli -g${wpa_conf} interface_remove ${ifname} 2>/dev/null 1>&2
	[ -n ${apvap} ] && iwconfig ${apvap} channel ${apchannel} 2>/dev/null 1>&2
	wlanconfig ${ifname} destroy 2>/dev/null 1>&2
	kill "$(cat /var/run/wpa_supplicant.pid)" 2>/dev/null
	echo "$1 connection check succeed."
	return 0
} || {
	wpa_cli -p${wpa_ctrl} -i${ifname} disconnect 2>/dev/null 1>&2
	wpa_cli -g${wpa_conf} interface_remove ${ifname} 2>/dev/null 1>&2
	[ -n ${apvap} ] && iwconfig ${apvap} channel ${apchannel} 2>/dev/null 1>&2
	wlanconfig ${ifname} destroy
	echo "$1 connection check fail!!!"
	return 1
}


