#!/bin/sh /etc/rc.common

START=19

RADIO_24G=
find_2_4_radio() {
	local cfg=$1

	local hwmode
	config_get hwmode "$cfg" hwmode
	[ "$hwmode" = "11ng" ] && RADIO_24G=$cfg
}

APVAP_24G=
find_2_4_apvap() {
	local cfg=$1
	local radio=$2

	local mode
	config_get mode "$cfg" mode
	local device
	config_get device "$cfg" device

	[ "$mode" = "ap" -a "$device" = "$radio" ] && \
		APVAP_24G="$cfg"
}

start() {
	config_load system
	local state
	state=$(uci_get system @system[0] state)
	[ "${state}" = "config_complete" ] && return 0

	config_load wireless

	config_foreach find_2_4_radio wifi-device
	[ -z "${RADIO_24G}" ] && {
		echo "Error: No 2.4GHz radio found"
		return 1
	}

	config_foreach find_2_4_apvap wifi-iface ${RADIO_24G}
	[ -z "${APVAP_24G}" ] && {
		echo "Error: No 2.4GHz AP VAP found"
		return 1
	}

	# Ok, now we start setting the Skifta configuration parameters
	local macaddr
	config_get macaddr ${RADIO_24G} macaddr
	uci_set wireless ${RADIO_24G} disabled 0
	uci_set wireless ${RADIO_24G} channel 6
	uci_set wireless ${APVAP_24G} ssid "Skifta ${macaddr:6:12}"
	uci_commit wireless

	uci_add_list dhcp @dnsmasq[0] address /#/172.19.42.1
	uci_commit dhcp

	uci_set uhttpd main error_page /index.html
	uci_commit uhttpd

        uci_set network lan ipaddr 172.19.42.1
        uci_commit network

	# We don't want to see DLNA services until the config is complete so we
	# disable them here. They will be enabled back during the configuration
	# process
	/etc/init.d/rygel disable
	/etc/init.d/orb disable

	STATE=config_oob /etc/statemgr
}
